theme: jekyll-theme-merlot

---
title: Linea y Lineo, un microrelato cartesiano
permalink: /projector/index.html
---

---
title: Linea y Lineo, un microrelato cartesiano
permalink: /torrent/index.html
---