theme: jekyll-theme-merlot

---
title: Linea y Lineo, un microrelato cartesiano
permalink: /projector/index.html
---

---
title: Linea y Lineo, un microrelato cartesiano
permalink: /torrent/index.html
---

---
title: Linea y Lineo, un microrelato cartesiano - Credits
permalink: /components/credits.html
---

---
title: Linea y Lineo, un microrelato cartesiano - cc-by-sa
permalink: /components/licencia.html
---

---
title: Linea y Lineo, un microrelato cartesiano - Embed it!
permalink: /components/embedIt.html
---

---
title: Linea y Lineo, un microrelato cartesiano - Contribute
permalink: /components/contribute.html
---

